### ISSUE TITLE
Pod module is not visible in project

### ISSUE THREAD

**Issue by mcontin** [adform/adform-tracking-ios-sdk#15]
When installing the pod in a Swift project, even if using "use_frameworks!" the module is not loaded in the project and it can't be imported in any file.

**Comment by mcontin** [comment]
Fixed by adding 
`#import <AdformTracking/AdformTracking.h>`
to the bridging header file.

**Comment by alessandroaime** [comment]
I tried both cocoapods and manual installations (`v1.3.1`), as well as tried @mcontin solution but still getting `No such module` when trying to import it. It seems that it doesn't even produce the AdForm framework for some reason.
