### ISSUE TITLE
Core Data model incompatible when updating from 0.1.6 to 0.2

### ISSUE THREAD

**Issue by andepopande** [adform/adform-tracking-ios-sdk#2]
I am updating from version 0.1.6 and get Core Data crashes on startup. Seems like the model has changed in a way the automatic database merging is not working any more.
```
<AdformTrakingSDK | error> Der Vorgang konnte nicht abgeschlossen werden. (Cocoa-Fehler 134110.)
CoreData: error: -addPersistentStoreWithType:SQLite configuration:(null) URL:file:///var/mobile/Containers/Data/Application/D25305D9-EDDF-455B-810E-169113DA50F7/Documents/RequestsModel.sqlite options:(null) ... returned error Error Domain=NSCocoaErrorDomain Code=134100 "Der Vorgang konnte nicht abgeschlossen werden. (Cocoa-Fehler 134100.)" UserInfo=0x177eb970 {metadata={
    NSPersistenceFrameworkVersion = 519;
    NSStoreModelVersionHashes =     {
        Request = <a89c2662 050b032d 29d3b638 5fe48b05 da1fdaac 2bf3f52c a5752986 7c2abb4b>;
    };
    NSStoreModelVersionHashesVersion = 3;
    NSStoreModelVersionIdentifiers =     (
        ""
    );
    NSStoreType = SQLite;
    NSStoreUUID = "A3DA620E-8E42-495B-BA1C-80F53C542807";
    "_NSAutoVacuumLevel" = 2;
}, reason=The model used to open the store is incompatible with the one used to create the store} with userInfo dictionary {
    metadata =     {
        NSPersistenceFrameworkVersion = 519;
        NSStoreModelVersionHashes =         {
            Request = <a89c2662 050b032d 29d3b638 5fe48b05 da1fdaac 2bf3f52c a5752986 7c2abb4b>;
        };
        NSStoreModelVersionHashesVersion = 3;
        NSStoreModelVersionIdentifiers =         (
            ""
        );
        NSStoreType = SQLite;
        NSStoreUUID = "A3DA620E-8E42-495B-BA1C-80F53C542807";
        "_NSAutoVacuumLevel" = 2;
    };
    reason = "The model used to open the store is incompatible with the one used to create the store";
}
```

**Comment by aliuspetraska** [comment]
Hi @andepopande, thanks for reporting an issue, can you provide more details on your upgrading workflow? As our team can't reproduce the exact issue;

**Comment by andepopande** [comment]
I integrated version 0.1.6 into our app in October and installed in on my device.
Now I removed 0.1.6 and added 0.2 to our app and installed the app on my device without deleting the old one.

**Comment by vladasdrejeris** [comment]
Hi @andepopande, are you writing/deleting any/all files in application documents directory?

**Comment by andepopande** [comment]
Yes, I am deleting some file, but I do not delete the RequestsModel* files. Are there any other files that have to be kept?

**Comment by vladasdrejeris** [comment]
Are you sure that you don't delete RequestsModel.momd file? Can you make sure that it is in the documents directory in the app before the update? After the update to 0.2 this file should be replaced with RequestsModel.plist.

**Comment by andepopande** [comment]
There are 3 files listed in the documents folder for old 0.1.6 version: RequestsModel.sqlite, RequestsModel.sqlite-shm and RequestsModel.sqlite-wal. 
The new 0.2.0 version lists following files while crashing: RequestsModel.plist, RequestsModel.sqlite, RequestsModel.sqlite-shm and RequestsModel.sqlite-wal. 
The app is crashing before I even try to cleanup files in documents folder.

There is no momd file in documents folder. The momd file which was available in 0.1.6 is not available in the 0.2 zip file. I don't know if the file is now somehow bundled in the framework binary file.

**Comment by vladasdrejeris** [comment]
On 0.1.6 version there should be these files in documents directory: RequestsModel.momd, RequestsModel.sqlite, RequestsModel.sqlite-shm and RequestsModel.sqlite-wal. 
There is no RequestsModel.momd file in your 0.1.6 version app, therefore when SDK tries to update to a new version it cannot find the model of the old database and crashes.
Maybe you delete it on 0.1.6 version app while it is running.
The new framework build of the sdk doesn't have .momd file (sdk reads it from documents directory only for the database migration), it creates a new database model programmatically.

**Comment by andepopande** [comment]
Hmm strange, there is no such file in documents folder. I do not delete anything. Tested it several times.
The momd is located inside the app bundle in the aft_resources.bundle - but not in the documents folder. When exactly is this file copied?

**Comment by andepopande** [comment]
Ahh I think I found the issue. The momd was actually deleted on our own clients. So the app update with 0.2 included will not have the momd file. What is your recommendation how to preceed? 
1. Should we bundle the old momd, copy it manually to documents folder before starting the Adform SDK.
or
2. remove all RequestsModel sqlite files before starting the Adform SDK?

**Comment by vladasdrejeris** [comment]
Both methods should work, but you need to do this only once. Don't copy or delete these files on every app launch, because it will cause other problems. 
You could check if there is neither one of RequestsModel.momd (used in 0.1.6 v.) and RequestsModel.plist (used in 0.2 v.) files, but the database files exist, in documents directory and then copy the RequestsModel.momd from you resources to application folder.
And make sure that you don't delete the RequestsModel.plist in the future.

**Comment by andepopande** [comment]
Okay thanks for your help.
