### ISSUE TITLE
Multiple warnings when compiling project with your SDK

### ISSUE THREAD

**Issue by lmktrifork** [adform/adform-tracking-ios-sdk#3]
Hi 
We are getting the following warnings when building our project with your SDK/Pod added:
warning: /tmp/xxx/xxx_objc/build/DerivedData/ModuleCache/Y223BTTTTU2N/Foundation-xxxxx.pcm: No such file or directory

Please recompile your project with "Precompile Prefix Header" set to "No" and update the Pod.

See the following:
https://github.com/realm/realm-cocoa/issues/2642
https://forums.developer.apple.com/thread/17921

We are having the same problem as they are describing in the links above.

**Comment by Mindulis** [comment]
Hi,
we are investigating the problem and will inform you as soon as there will be some news.

**Comment by Mindulis** [comment]
Hi,
we released fix for the problem, please update your SDK.

**Comment by lmktrifork** [comment]
I can see that you have reopened the issue? still not fixed or are you for us to test it before closing it?

**Comment by Mindulis** [comment]
Sorry, i  miss clicked so issue was reopened. It should be fixed.
