### ISSUE TITLE
Missing bitcode

### ISSUE THREAD

**Issue by alessandroorru** [adform/adform-tracking-ios-sdk#5]
Bitcode seems to be disabled for this library. Is it possible to have an updated version?

`ld: bitcode bundle could not be generated because 'Pods/AdformTracking/AdformTracking.framework/AdformTracking(LoggingHelper.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7`

**Comment by vladasdrejeris** [comment]
Hello,

We have released a new sdk version that supports bitcode. Try to update.

**Comment by alessandroorru** [comment]
Just tried using the updated 0.2.6 podspec, it works as expected 👍

Thank you!
