### ISSUE TITLE
Runtime Error : 

### ISSUE THREAD

**Issue by ravichokshi** [adform/adform-tracking-ios-sdk#6]
Hi
i could build and run project but as soon it run , it throws error :

 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[GPBDescriptor allocDescriptorForClass:rootClass:file:fields:fieldCount:oneofs:oneofCount:enums:enumCount:ranges:rangeCount:storageSize:wireFormat:]: unrecognized selector sent to class 0x107e2a578'

**Comment by vladasdrejeris** [comment]
Hello,

How did you integrate our SDK through Cocoapods or manually?

**Comment by ravichokshi** [comment]
Manually ..

**Comment by ravichokshi** [comment]
[AdDemo.zip](https://github.com/adform/adform-tracking-ios-sdk/files/306669/AdDemo.zip)

hi,
here is sample Ad code i created from your Framework manually. simply Run it, and it will crash . 

thanks .. !!

**Comment by vladasdrejeris** [comment]
Which version of Google Protobuf library are you using?

**Comment by ravichokshi** [comment]
Latest from Github : e34c091 revision

https://github.com/google/protobuf/tree/master/objectivec#building

**Comment by vladasdrejeris** [comment]
There may be an issue with protobuf version, try using an older one. Cocoapods installation uses 3.0.0-alpha-4 version of protobuf and works fine.

**Comment by ravichokshi** [comment]
Thanks .. Great .. it works ... thanks a ton for help .. !! really appreciate ...

**Comment by vladasdrejeris** [comment]
No problem.
