### ISSUE TITLE
Errors when using Cocoapods with use_framework

### ISSUE THREAD

**Issue by AntonGolikov** [adform/adform-tracking-ios-sdk#7]
I have swift project and use_frameworks! for cocoapods is mandatory for me. But with that said Protobuf's 3.0.0-alpha version do not compile because of imports like 

`#import "google/protobuf/Empty.pbobjc.h"`

According to the [issue](https://github.com/google/protobuf/issues/1651), Protobuf's team already fixed it in cuccent version 3.0.0-beta-3.1.

So I decided to drop Adform framework manualy in the project and add Protobuf via cocoapods. But my application started to crash. I belive Protobuf uses new syntax or something else. please take a look at the actual log:

> 2016-06-22 17:46:35.690 TheApplication[1344:8828] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[GPBDescriptor allocDescriptorForClass:rootClass:file:fields:fieldCount:oneofs:oneofCount:enums:enumCount:ranges:rangeCount:storageSize:wireFormat:]: unrecognized selector sent to class 0x10af992c8'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109cc4d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010d2fadeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000109ccdc3d +[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000109c13cfa ___forwarding___ + 970
	4   CoreFoundation                      0x0000000109c138a8 _CF_forwarding_prep_0 + 120
	5   TheApplication                      0x0000000108d022e9 +[SdkData descriptor] + 256
	6   Protobuf                            0x000000010af50fe1 +[GPBMessage initialize] + 177
	7   libobjc.A.dylib                     0x000000010d2fbbff _class_initialize + 679
	8   libobjc.A.dylib                     0x000000010d301cc5 lookUpImpOrForward + 176
	9   libobjc.A.dylib                     0x000000010d3108bb objc_msgSend + 187
	10  TheApplication                      0x0000000108cfe5ff -[AFTTrackingDataBuilder pbSdkDataFromAFTrackingData:] + 72
	11  TheApplication                      0x0000000108cfe3f5 -[AFTTrackingDataBuilder build] + 66
	12  TheApplication                      0x0000000108d0a869 -[AFTrackingURLBuilder makeTrackingData] + 202
	13  TheApplication                      0x0000000108d0a314 -[AFTrackingURLBuilder makeQueryParameters] + 451
	14  TheApplication                      0x0000000108d0a0be -[AFTrackingURLBuilder build] + 31
	15  TheApplication                      0x0000000108d0191f -[AFTrackingPointDispatcher dispatchTrackpoint:] + 221
	16  TheApplication                      0x0000000108d01705 -[AFTrackingPointDispatcher sendRequestForTrackpoint:] + 92
	17  TheApplication                      0x0000000108d01658 __51-[AFTrackingPointDispatcher sendPendingTrackpoints]_block_invoke + 204
	18  Foundation                          0x000000010cf6d630 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	19  Foundation                          0x000000010cea8805 -[NSBlockOperation main] + 101
	20  Foundation                          0x000000010ce8b725 -[__NSOperationInternal _start:] + 646
	21  Foundation                          0x000000010ce8b336 __NSOQSchedule_f + 194
	22  libdispatch.dylib                   0x000000010e9813eb _dispatch_client_callout + 8
	23  libdispatch.dylib                   0x000000010e9691ef _dispatch_main_queue_callback_4CF + 1738
	24  CoreFoundation                      0x0000000109c1e0f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	25  CoreFoundation                      0x0000000109bdfb99 __CFRunLoopRun + 2073
	26  CoreFoundation                      0x0000000109bdf0f8 CFRunLoopRunSpecific + 488
	27  GraphicsServices                    0x000000011107fad2 GSEventRunModal + 161
	28  UIKit                               0x000000010b7b1f09 UIApplicationMain + 171
	29  TheApplication                      0x0000000108b01742 main + 114
	30  libdyld.dylib                       0x000000010e9b592d start + 1
	31  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

I hope you can release a new version soon with frameworks support. Thanks

**Comment by vladasdrejeris** [comment]
We have released a new SDK version that should fix you issue.

**Comment by AntonGolikov** [comment]
Seems working. Thanks. But I'm little concern about you're using `Protobuf alpha-4.1` as dependency, and I'm forced to use `Protobuf beta-3.1`, because that exact version they fixed framework issue.

I mean my integration solution for adform stays the same, I manually add the framework to my project and add the latest Protobuf beta via Cocoapods. Is this gonna work just fine?

**Comment by vladasdrejeris** [comment]
We have updated the sdk to use the newest Protobuf version (beta-3.1), therefore you can just integrate it through cocoapods, we no longer depend on alpha-4.1.
