### ISSUE TITLE
Lacking iOS10 support?

### ISSUE THREAD

**Issue by jimmaye** [adform/adform-tracking-ios-sdk#8]
Hi

I've just upgraded my iPhone 6S to the iOS 10.0.1 GM seed, and suddenly the AdFormTracking SDK stops reporting anything. I've also tried it out in iOS10 simulators, and still the SDK doesn't report anything. When switching to iOS9, all tracking points gets sent successfully as excepted.

Do I need to configure ATS in someway or the other?

Any hint or tip to get it working again is much appreciated!

**Comment by vladasdrejeris** [comment]
Hello, 

We are aware of this issue on iOS 10 and are working to solve it at the moment.
We will soon release an sdk update that fixes it.

**Comment by jimmaye** [comment]
Sound good, thank you!

**Comment by vladasdrejeris** [comment]
Try using the new 1.1.2 version of the sdk.
